name: bank-api
version: "3.9"

# =====================================================================
#  Docker compose file for bank-api, bank-seq
# =====================================================================
# Call via the makefile, otherwise you'll need to set all the vars!
# Use with `make docker-build`, `make docker-push` & `make docker-run`
# =====================================================================

services:

  bank-api:
    image: ${IMAGE_PREFIX}/bank-api:${IMAGE_TAG}
    pull_policy: build
    container_name: bank-api
    build:
      context: .
      dockerfile: src/Payment.Bank.Api/Dockerfile
      args:
        VERSION: ${VERSION}
        BUILD_INFO: ${BUILD_INFO}
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - bank-seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTP_PORT=5000
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_PATHBASE=/bank-api
      - ASPNETCORE_Kestrel__Certificates__Default__Password=devcertpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - BANK_Serilog:WriteTo:1:Args:serverUrl=http://bank.seq:80
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - bank-network
    restart: on-failure

  bank-seq:
    image: datalust/seq:latest
    container_name: bank-seq
    restart: always
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - bank-network

networks:
  bank-network:
    name: bank-network
    driver: bridge
