title: Bank Microservice
email: salzaki@example.com
description: Bank Microservice pages.
baseurl: ""
url: ""
twitter_username: sal_zaki
github_username:  salzaki

aux_links:
  "SalZaki.Bank on GitHub": https://github.com/salzaki/Bank

theme: just-the-docs
plugins:
  - jekyll-feed
